files: .py$
default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        stages:
          - commit
          - manual
        additional_dependencies: [flake8-bugbear]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        stages:
          - commit

      - id: black
        name: black-check
        args:
          - --check
          - --diff
        stages:
          - manual

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        stages:
          - commit

      - id: isort
        name: isort-check
        args:
          - --check-only
        stages:
          - manual

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        pass_filenames: false
        args:
          - -r
          - app
