services:
  backend:
    build:
      context: app
    command: ["uvicorn", "--host", "0.0.0.0", "--port", "8030", "--factory", "main:create_app", "--reload"]
    ports:
      - 8030:8030
    environment:
      - DEBUG
      - CLIENT_ID
      - CLIENT_SECRET
      - SECRET_KEY
    volumes:
      - ./app:/opt/app
