- hosts: all
  vars:
    app_path: /opt/app
  tasks:
    - name: Create app directory
      become: true
      file:
        path: "{{ app_path }}"
        state: directory

    - name: Copy app files
      become: true
      copy:
        src: "{{ item }}"
        dest: "{{ app_path }}"
      with_items:
        - "docker-compose.yml"
        - ".env"

    - name: Start services
      docker_compose:
        project_src: "{{ app_path }}"
        state: present
      register: app_state

    - name: Check the app is running
      assert:
        that:
          - "app_state.services.backend.app_backend_1.state.running"
          - "app_state.services.traefik.app_traefik_1.state.running"
        success_msg: "App is running"
        fail_msg: "App is not running"

    - name: Cleanup images
      shell: docker image prune -f
      args:
        warn: no
