api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      caServer: ${CASERVER}
      email: ${CERT_EMAIL}
      storage: "letsencrypt/acme.json"
      httpChallenge:
        entryPoint: web
