name: Build and publish to YC Container Registry

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      yc_cr_id: ${{ secrets.YC_CR_ID }}

    steps:
      - uses: actions/checkout@v2

      - name: Log in YC CR
        run: docker login -u oauth -p ${{ secrets.YC_TOKEN }} cr.yandex

      - name: Build the app
        run: docker build -t $yc_cr_id/spotify-playlist-saver:latest ./app

      - name: Push the image
        run: docker push $yc_cr_id/spotify-playlist-saver:latest
