name: Deploy to YC Compute Cloud

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create dotenv
        run: echo "${{ secrets.ENV }}" > .env

      - name: Create SSH key
        run: touch .ssh-key && chmod 700 .ssh-key && echo "${{ secrets.INSTANCE_SSH_KEY }}" > .ssh-key

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install ansible

      - name: Deploy
        env:
          ssh_user: ${{ secrets.INSTANCE_USER }}
          ssh_key_file: .ssh-key
          host: ${{ secrets.HOST }}
          ANSIBLE_HOST_KEY_CHECKING: false
        run: ansible-playbook playbook.yml -i inventory.yml
