name: Build and deploy to YC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      yc_cr_id: ${{ secrets.YC_CR_ID }}

    steps:
      - uses: actions/checkout@v2

      - name: Log in YC CR
        run: docker login -u oauth -p ${{ secrets.YC_TOKEN }} cr.yandex

      - name: Build the app
        run: docker build -t $yc_cr_id/spotify-playlist-saver:latest ./app

      - name: Push the image
        run: docker push $yc_cr_id/spotify-playlist-saver:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Create dotenv
        run: echo "${{ secrets.ENV }}" > .env

      - name: Create SSH key
        run: echo "${{ secrets.INSTANCE_SSH_KEY }}" > .ssh-key

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install ansible

      - name: Deploy
        env:
          ssh_user: ${{ secrets.INSTANCE_USER }}
          ssh_key_file: .ssh-key
          host: ${{ secrets.HOST }}
          ANSIBLE_HOST_KEY_CHECKING: false
        run: ansible-playbook playbook.yml -i inventory.yml
